// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./components/common/jContainer/src/aside.vue')['default']
    Footer: typeof import('./components/common/jContainer/src/footer.vue')['default']
    Header: typeof import('./components/common/jContainer/src/header.vue')['default']
    Index: typeof import('./components/common/jContainer/src/Index.vue')['default']
    RightContent: typeof import('./components/RightContent/RightContent.vue')['default']
  }
}

export { }
