// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Index: typeof import('./components/common/jTable/src/Index.vue')['default']
    RightContent: typeof import('./components/RightContent/RightContent.vue')['default']
  }
}

export { }
